server:
  port: 8765
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: usuario-service
        uri: lb://usuario-service
        predicates:
        - Path=/usuario-service/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
