server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka 
spring:
  application:
    name: usuario-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usuario_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: 2211
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
springdoc:
  api-docs:
    path: cambio-service/v3/api-docs